Agrego scrip para movimiento del Player
gamerevar/proyecto-comunitario-1-unity pull request #14
Opened 2020-12-30 22:36 UTC by AgustinAllamanoCosta

Agrego script para el movimiento del player segun lo especificado en https://open.codecks.io/proyecto-comunitario-1-unity/decks/10-programación/card/14j-movimiento-del-jugador

2020-12-30 22:41 UTC, gamerevar commented
@Svartskogen fijate que hay archivos .meta, etc, que se modificaron. Avisen si hay que agregarlos al .gitignore.

2020-12-30 22:50 UTC, AgustinAllamanoCosta commented
Tengo entendido que el packages-lock.json tiene que ir porque tiene las dependencias que se agregen asi que ese no se tendira que ignorar por si en algun futuro alguien agrega una .dll, lo que no se bien son los otros. Ahora me pongo a leer la documentancion para ver si son super necesarios.

2020-12-30 22:52 UTC, Svartskogen commented
Esos archivos están bien, los .meta son necesarios. lo del packages-lock.json creo que simplemente actualizo el paquete de testing, no hay problema con eso tampoco.
Mas tarde reviso bien el código.

2020-12-31 02:29 UTC, Svartskogen commented
Bien, ya lo revise y hay varias cositas por ajustar:

- La variable _speed_ podría tener el atributo [SerializeField], y dejar como valor por defecto 100.0f, quitando esta asignación de la linea 16 asi nos deja cambiar la velocidad del jugador desde el Inspector.

- En la linea 17 no hace falta "_gameObject._", el _GetComponent_ solo es suficiente, un detalle solamente

- No tiene mucho sentido usar _Time.deltaTime_ en un **FixedUpdate**, podríamos mover todo el codigo de **FixedUpdate** a **Update** y quedaría bien.

- Por ultimo el vector _speedVector_ debería estar normalizado antes de pasarlo al calculo de la velocidad final, ya que esto causaría que el jugador se mueva mas rápido al entrar inputs verticales y horizontales al mismo tiempo.

Con esas cositas arregladas ya quedaría listo para integrarlo a master!

2020-12-31 02:42 UTC, AgustinAllamanoCosta commented
Con el vector normalizado a que te referiz?  por lo que yo se un vectornormalizado es el que se dividido por su magnitud y te da norma 1

2020-12-31 02:52 UTC, Svartskogen commented
> Con el vector normalizado a que te referiz? por lo que yo se un vectornormalizado es el que se dividido por su magnitud y te da norma 1

Exactamente, el vector que le pasamos por el Input tiene que ser un vector dirección, por convención los vectores dirección siempre están normalizados.
Esto es para impedir que el vector tenga una magnitud mas grande que 1 cuando recibe varios inputs, para normalizarlo simplemente pasalo como "_speedVector.normalized_" en la linea 35

2020-12-31 02:56 UTC, AgustinAllamanoCosta commented
Si si matematicamente tiene todo el sentido, pero viendolo asi pense que seria mejor usar una fuerza en nuestro caso, mas sabiendo que iba a hacer 2d y lo vamos a mover en todas las direcciones. Ahora me pongo ocn los cambios (tengo que esperar a mi tostadora levante el otro unity)

2020-12-31 13:38 UTC, Svartskogen requested changes
Fijate que por mas que ahora speed sea un SerializeField, en Start, línea 15 se le setea un valor fijo. Esto causaría que no importa que valor le asignemos en el inspector, el valor siempre va a ser 10.0f, podrías probar de sacar la línea 15 así ya queda con el valor que le asignemos en el Inspector.
El resto se ve bien!

2021-01-11 00:36 UTC, Svartskogen approved these changes
Ya todo listo para integrarlo a master.

2021-01-11 00:36 UTC, merged